# Generated by Django 4.0.1 on 2022-02-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/home/nika/PycharmProjects/learning_django/media/profile_pics/profile_pic.png', upload_to='profile_pics'),
        ),
    ]
